#!/usr/bin/env python

bld.program(
    packages     = ['glib-2.0', 'libsoup-2.4', 'lua'],
    target       = 'app',
    source       = 'app.vala',
    use          = 'valum',
    uselib       = ['GLIB', 'CTPL', 'GEE', 'SOUP', 'LUA', 'GCOV'],
    vapi_dirs    = ['../../vapi'],
    install_path = None)
