#!/usr/bin/env python

def configure(cfg):
    cfg.check_cfg(package='gio-unix-2.0', atleast_version='2.32')

    # libsoup (>=2.48) is necessary for the new server API
    if cfg.check_cfg(package='libsoup-2.4', atleast_version='2.48', mandatory=False, uselib_store='SOUP', args='--cflags --libs'):
        cfg.env.append_unique('VALAFLAGS', ['--define=SOUP_2_48'])

    # libsoup (>=2.50) for steal_connection
    if cfg.check_cfg(package='libsoup-2.4', atleast_version='2.50', mandatory=False, uselib_store='SOUP', args='--cflags --libs'):
        cfg.env.append_unique('VALAFLAGS', ['--define=SOUP_2_50'])

def build(bld):
    from waflib import Context
    bld.shlib(
        target       = 'vsgi-http',
        gir          = 'VSGI.HTTP-{}'.format(Context.g_module.API_VERSION),
        source       = 'vsgi-http.vala',
        use          = 'vsgi',
        header_path  = '${INCLUDEDIR}/vsgi',
        install_path = '${LIBDIR}')

    bld(
        features     = 'subst',
        target       = 'vsgi-http.pc',
        source       = 'vsgi-http.pc.in',
        install_path = '${LIBDIR}/pkgconfig',
        VERSION      = Context.g_module.VERSION)

