#!/usr/bin/env python

def configure(cfg):
    pass

def build(bld):
    bld.program(
        target       = 'app',
        use          = 'valum',
        source       = ['app.vala'],
        vapi_dirs    = '../../vapi',
        install_path = None)
