#!/usr/bin/env python

def configure(cfg):
    pass

def build(bld):
    from waflib import Context
    bld.shlib(
        target       = 'vsgi-scgi',
        gir          = 'VSGI.SCGI-{}'.format(Context.g_module.API_VERSION),
        source       = 'vsgi-scgi.vala',
        use          = 'vsgi vsgi-cgi',
        vala_defines = 'INCLUDE_TYPE_MODULE',
        header_path  = '${INCLUDEDIR}/vsgi',
        install_path = '${LIBDIR}')

    bld(
        features     = 'subst',
        target       = 'vsgi-scgi.pc',
        source       = 'vsgi-scgi.pc.in',
        install_path = '${LIBDIR}/pkgconfig',
        VERSION      = Context.g_module.VERSION,
        API_VERSION  = Context.g_module.API_VERSION)
