#!/usr/bin/env python

bld.program(
    packages     = ['glib-2.0'],
    target       = 'tests',
    use          = 'valum',
    source       = ['tests.vala'] + bld.path.ant_glob('**/test_*.vala'),
    uselib       = ['GLIB', 'CTPL', 'GEE', 'SOUP', 'FCGI', 'GCOV'],
    vapi_dirs    = ['../vapi'],
    install_path = None)
