#!/usr/bin/env python

bld.program(
    packages     = ['glib-2.0', 'libsoup-2.4', 'json-glib-1.0', 'ctpl'],
    target       = 'app',
    source       = 'app.vala',
    use          = 'valum',
    uselib       = ['GLIB', 'GEE', 'CTPL', 'SOUP', 'JSON'],
    install_path = None)
