#!/usr/bin/env python

def configure(cfg):
    cfg.check_cfg(package='json-glib-1.0', uselib_store='JSON', args='--cflags --libs')

def build(bld):
    bld.program(
        packages     = ['glib-2.0', 'libsoup-2.4', 'json-glib-1.0', 'ctpl'],
        target       = 'app',
        source       = 'app.vala',
        use          = 'valum JSON',
        install_path = None)
