#!/usr/bin/env python

def configure(cfg):
    pass

def build(bld):
    from waflib import Context
    bld.shlib(
        target       = 'valum',
        gir          = 'Valum-{}'.format(Context.g_module.API_VERSION),
        source       = bld.path.ant_glob('*.vala'),
        use          = 'vsgi',
        header_path  = '${INCLUDEDIR}/valum',
        install_path = '${LIBDIR}')

    bld(
        features     = 'subst',
        target       = 'valum.pc',
        source       = 'valum.pc.in',
        install_path = '${LIBDIR}/pkgconfig',
        VERSION      = Context.g_module.VERSION)
