#!/usr/bin/env python

def configure(cfg):
    cfg.check_cfg(package='gio-unix-2.0', atleast_version='2.32', uselib_store='GIOUNIX', args='--cflags --libs')

def build(bld):
    from waflib import Context
    bld.shlib(
        packages_private = 'gio-unix-2.0',
        target           = 'vsgi-cgi',
        gir              = 'VSGI.CGI-{}'.format(Context.g_module.API_VERSION),
        source           = 'vsgi-cgi.vala',
        use              = 'vsgi',
        uselib           = 'GIOUNIX',
        header_path      = '${INCLUDEDIR}/vsgi',
        install_path     = '${LIBDIR}')

    bld(
        features     = 'subst',
        target       = 'vsgi-cgi.pc',
        source       = 'vsgi-cgi.pc.in',
        install_path = '${LIBDIR}/pkgconfig',
        VERSION      = Context.g_module.VERSION)

