#!/usr/bin/env python

def configure(cfg):
    cfg.check(lib='markdown', uselib_store='MARKDOWN', args='--cflags --libs')

def build(bld):
    bld.program(
        packages     = ['libmarkdown'],
        target       = 'app',
        source       = 'app.vala',
        use          = 'valum MARKDOWN',
        vapi_dirs    = ['vapi', '../../vapi'],
        install_path = None)
