#!/usr/bin/env python

bld.program(
    packages     = ['glib-2.0', 'libmemcached'],
    target       = 'app',
    source       = 'app.vala',
    use          = 'valum',
    uselib       = ['GLIB', 'SOUP', 'GEE', 'MEMCACHED'],
    install_path = None,
    vapi_dirs    = ['../../vapi', 'vapi'])
