#!/usr/bin/env python

bld.program(
    packages     = ['glib-2.0', 'libsoup-2.4', 'json-glib-1.0'],
    target       = 'app',
    use          = 'valum',
    source       = 'app.vala',
    uselib       = ['GLIB', 'CTPL', 'GEE', 'SOUP', 'JSON', 'GCOV'],
    vapi_dirs    = ['../../vapi'],
    install_path = None)
