#!/usr/bin/env python

def configure(cfg):
    cfg.check_cfg(package='json-glib-1.0', uselib_store='JSON', args='--cflags --libs')

def build(bld):
    bld.program(
        packages     = ['json-glib-1.0'],
        target       = 'app',
        use          = 'valum JSON',
        source       = 'app.vala',
        install_path = None)
