#!/usr/bin/env python

from waflib import Context

# RPM specfile
bld(
    features     = 'subst',
    target       = 'valum.spec',
    source       = ['valum.spec.in'],
    install_path = None,
    VERSION      = Context.g_module.VERSION)
