#!/usr/bin/env python

from waflib import Context

# pkg-config file
bld(
    features     = 'subst',
    target       = 'valum.pc',
    source       = ['valum.pc.in'],
    install_path = '${LIBDIR}/pkgconfig',
    VERSION      = Context.g_module.VERSION,
    API_VERSION  = Context.g_module.API_VERSION)

# RPM specfile
bld(
    features     = 'subst',
    target       = 'valum.spec',
    source       = ['valum.spec.in'],
    install_path = None,
    VERSION      = Context.g_module.VERSION)
