#!/usr/bin/env python

bld.program(
    packages     = ['glib-2.0'],
    target       = 'fastcgi',
    use          = 'valum',
    source       = ['app.vala'],
    uselib       = ['GLIB', 'SOUP', 'GEE', 'FCGI', 'GCOV'],
    vapi_dirs    = ['../../vapi'],
    install_path = None,
    threding     = True)

bld(
    rule   = 'cp ${SRC} ${TGT}',
    target = bld.path.get_bld().make_node('start'),
    source = bld.path.make_node('start'))
