#!/usr/bin/env python

def configure(cfg):
    pass

def build(bld):
    bld.program(
        packages     = ['glib-2.0'],
        target       = 'fastcgi',
        use          = 'valum',
        source       = ['app.vala'],
        install_path = None)

