#!/usr/bin/env python

def configure(cfg):
    pass

def build(bld):
	bld.program(
            target       = 'app',
            use          = 'valum',
            source       = 'app.gs',
            uselib       = ['GEE', 'SOUP'],
            install_path = None)
