#!/usr/bin/env python

def configure(cfg):
    pass

def build(bld):
	bld.program(
        target       = 'app',
        source       = 'app.gs',
        use          = 'valum',
        vapi_dirs    = '../../vapi',
        install_path = None)
