#!/usr/bin/env python

bld.program(
    package   = ['libsoup-2.4', 'ctpl'],
    target    = 'app',
    use       = 'valum',
    source    = ['app.vala'],
    uselib    = ['CTPL', 'SOUP', 'GEE'],
    vapi_dirs = ['../../vapi'])
