#!/usr/bin/env python

bld.program(
    packages  = ['glib-2.0'],
    target    = 'app',
    use       = 'valum',
    source    = ['app.vala'],
    uselib    = ['GLIB', 'SOUP', 'GEE', 'CTPL'],
    vapi_dirs = ['../../vapi'])
