#!/usr/bin/env python

def configure(cfg):
    pass

def build(bld):
    from waflib import Context
    bld.shlib(
        target       = 'vsgi-mock',
        gir          = 'VSGI.Mock-{}'.format(Context.g_module.API_VERSION),
        source       = 'vsgi-mock.vala',
        use          = 'vsgi',
        header_path  = '${INCLUDEDIR}/vsgi',
        install_path = '${LIBDIR}')

    bld(
        features     = 'subst',
        target       = 'vsgi-mock.pc',
        source       = 'vsgi-mock.pc.in',
        install_path = '${LIBDIR}/pkgconfig',
        VERSION      = Context.g_module.VERSION,
        API_VERSION  = Context.g_module.API_VERSION)

