#!/usr/bin/env python

def configure(cfg):
    cfg.find_program('sphinx-build', var='SPHINXBUILD')

def build(bld):
    bld.load('gnu_dirs')
    bld(
        rule   = '${SPHINXBUILD} -W -b html ${SRC[0].parent.abspath()} ${TGT}',
        target = '.',
        source = bld.path.ant_glob('*.rst') + bld.path.ant_glob('**/*.rst'))
