#!/usr/bin/env python

def configure(cfg):
    cfg.recurse('vsgi valum')
    cfg.recurse('vsgi-http vsgi-cgi vsgi-scgi vsgi-fastcgi vsgi-mock')

def build(bld):
    bld.recurse('vsgi valum')
    bld.recurse('vsgi-http vsgi-cgi vsgi-scgi vsgi-fastcgi vsgi-mock')

    # static bundle for tests and examples
    bld.stlib(
        packages         = 'glib-2.0 gio-2.0 gio-unix-2.0 libsoup-2.4',
        packages_private = 'fcgi',
        target           = 'valum',
        source           = bld.path.ant_glob('**/*.vala'),
        use              = 'GLIB GIO GIOUNIX SOUP FCGI GCOV',
        vapi_dirs        = 'vsgi-fastcgi',
        install_binding  = False,
        header_path      = None,
        install_path     = None)
