#!/usr/bin/env python

def configure(cfg):
    cfg.load('glib2')

def build(bld):
    bld.load('glib2')
    bld.program(
        target       = 'app',
        source       = ['app.vala', 'app.gresource.xml'],
        use          = 'valum',
        install_path = None)
