#!/usr/bin/env python

bld.program(
   packages     = ['libsoup-2.4', 'gee-0.8', 'ctpl', 'lua', 'libmemcached'],
   target       = 'app',
   use          = 'valum',
   source       = bld.path.ant_glob('**/*.vala'),
   uselib       = ['CTPL', 'GEE', 'SOUP', 'LUA', 'MEMCACHED'],
   vapi_dirs    = ['../../vapi', 'vapi'])
