#!/usr/bin/env python

bld.load('glib2')

bld.program(
    packages     = ['glib-2.0', 'libsoup-2.4', 'gee-0.8', 'ctpl'],
    target       = 'app',
    source       = ['app.vala', 'app.gresource.xml'],
    use          = 'valum',
    uselib       = ['GLIB', 'CTPL', 'GEE', 'SOUP', 'GCOV'],
    vapi_dirs    = ['../../vapi'],
    install_path = None)
