name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Vala PPA repository
        run: sudo add-apt-repository --yes ppa:vala-team

      - name: Update APT cache
        run: sudo apt-get update --quiet

      - name: Install dependencies
        run: sudo apt-get install --yes valac libglib2.0-bin libglib2.0-dev libsoup2.4-dev libsystemd-dev libfcgi-dev gcovr libgee-0.8-dev libctpl-dev libjson-glib-dev libmemcached-dev libmarkdown2-dev liblua5.2-dev valgrind meson ninja-build

      - name: Build
        run: |
          mkdir build
          meson -D b_coverage=true -D enable_examples=true . build
          ninja -C build -v
          ninja -C build -v docs/en

      - name: Test
        run: |
          meson test -C build --wrapper valgrind --print-errorlogs --num-processes=1 -v
          DESTDIR=$(mktemp -d) ninja -C build -v install

      - name: Generate coverage reports
        run: ninja -C build -v coverage

      - name: Report coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
